info_portal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('user_profile.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_profile/urls.py
from django.conf.urls import url
from . import views

app_name = 'user_profile'
urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^register/student/$', views.register, name='register'),
    url(r'^login/student/$', views.user_login, name='user_login'),
    url(r'^register/teacher/$', views.register_teacher, name='register_teacher'),
    url(r'^login/teacher/$', views.user_login_teacher, name='user_login_teacher'),
    url(r'^logout/student/$', views.logout_student, name='logout_student'),
    url(r'^logout/teacher/$', views.logout_teacher, name='logout_teacher'),
    url(r'^login/recruiter/$', views.user_login_recruiter,
        name='user_login_recruiter'),
    url(r'^logout/recruiter/$', views.logout_recruiter, name='logout_recruiter'),
    url(r'^student_profile/(\d+)$',
        views.student_profile, name='student_profile'),
    url(r'^notifications/$', views.notifs, name='notifs'),
    url(r'^search/$', views.student_list, name='student_list'),
    url(r'^teacherdashboard/$', views.teacher_dashboard, name='teacher_dashboard'),
    url(r'^search/$', views.student_list, name='student_list'),
    url(r'^internship/(\d+)$', views.internship, name='internship'),
    url(r'^hackathon/(\d+)$', views.hackathon, name='hackathon'),
    url(r'^project/(\d+)$', views.project, name='project'),
    url(r'^beproject/(\d+)$', views.beproject, name='beproject'),
    url(r'^committee/(\d+)$', views.committee, name='committee'),
    url(r'^researchpaper/(\d+)$', views.researchpaper, name='researchpaper'),
    url(r'^extracurricular/(\d+)$', views.extracurricular, name='extracurricular'),
    url(r'^searchany/', views.searchany, name='searchany'),
    url(r'^editprofile', views.show_edit_studentprofile, name='show_edit_studentprofile'),
    url(r'^edit_basic_info/(\d+)$', views.edit_basic_info),
    url(r'^edit_academic_info/(\d+)$', views.edit_academic_info),
    url(r'^edit_skill_info/(\d+)$', views.edit_skill_info),
    url(r'^edit_hackathon_info/(\d+)$', views.edit_hackathon_info),
    url(r'^edit_project_info/(\d+)$', views.edit_project_info),
    url(r'^edit_internship_info/(\d+)$', views.edit_internship_info),
    url(r'^edit_committee_info/(\d+)$', views.edit_committee_info),
    url(r'^edit_research_paper_info/(\d+)$', views.edit_research_paper_info),
    url(r'^edit_beproject_info/(\d+)$', views.edit_beproject_info),
    url(r'^delete_project_info/(\d+)$', views.delete_project_info),
    url(r'^delete_hackathon_info/(\d+)$', views.delete_hackathon_info),
    url(r'^delete_committee_info/(\d+)$', views.delete_committee_info),
    url(r'^delete_skill_info/(\d+)$', views.delete_skill_info),
    url(r'^delete_internship_info/(\d+)$', views.delete_internship_info),
    url(r'^delete_researchpaper_info/(\d+)$', views.delete_researchpaper_info),
    url(r'^delete_extra_info/(\d+)$', views.delete_extra_info),
    url(r'^edit_extra_info/(\d+)$', views.edit_extra_info),
]

user_profile/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.core.validators import URLValidator
from django.core.validators import MinValueValidator
from django.core.validators import MaxValueValidator
from django.db.models.signals import m2m_changed
from django.core.exceptions import ValidationError
from simple_history.models import HistoricalRecords
# import django_filters


class StudentProfile(models.Model):
    student = models.OneToOneField(User, on_delete=models.CASCADE, related_name='stud')
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    Sap_Id = models.BigIntegerField(
        validators=[MaxValueValidator(99999999999),
                    MinValueValidator(10000000000)], blank=True, null=True)
    sap = models.CharField(max_length=50, blank=True, null=True)
    department = models.CharField(max_length=50, blank=True, null=True)
    photo = models.FileField(blank=True, null=True)
    github_id = models.CharField(max_length=50, null=True, blank=True)
    bio = models.CharField(max_length=200, blank=True, null=True)
    GENDER_CHOICES = (
        ("Male", "Male"),
        ("Female", "Female"),
    )
    gender = models.CharField(
        max_length=6, choices=GENDER_CHOICES, blank=True, null=True)
    mobileNo = models.CharField(max_length=50, blank=True, null=True)
    YEAR_CHOICES = (
        ("FE", "First Year"),
        ("SE", "Second Year"),
        ("TE", "Third Year"),
        ("BE", "Final Year"),
    )
    year = models.CharField(
        max_length=20, choices=YEAR_CHOICES, blank=True, null=True)
    cgpa = models.DecimalField(
        blank=True, null=True, default=None, max_digits=4, decimal_places=2)

    class Meta:
        permissions = (
            ("view_student", "Can see student profile"),
        )

    def __str__(self):
        return str(str(self.Sap_Id) + '   ' + str(self.id))


class Recruiter(models.Model):
    recruiter = models.OneToOneField(User, on_delete=models.CASCADE)


class Education(models.Model):
    student_profile = models.ForeignKey(
        StudentProfile, related_name='education')
    sem1_gpa = models.DecimalField(
        blank=True, null=True, default=None, max_digits=4, decimal_places=2)
    sem2_gpa = models.DecimalField(
        blank=True, null=True, default=None, max_digits=4, decimal_places=2)
    sem3_gpa = models.DecimalField(
        blank=True, null=True, default=None, max_digits=4, decimal_places=2)
    sem4_gpa = models.DecimalField(
        blank=True, null=True, default=None, max_digits=4, decimal_places=2)
    sem5_gpa = models.DecimalField(
        blank=True, null=True, default=None, max_digits=4, decimal_places=2)
    sem6_gpa = models.DecimalField(
        blank=True, null=True, default=None, max_digits=4, decimal_places=2)
    sem7_gpa = models.DecimalField(
        blank=True, null=True, default=None, max_digits=4, decimal_places=2)
    sem8_gpa = models.DecimalField(
        blank=True, null=True, default=None, max_digits=4, decimal_places=2)
    history = HistoricalRecords()


class KT(models.Model):
    subject_name = models.CharField(max_length=100)
    SEM_CHOICES = (
        ("SEM1", "Semester 1"),
        ("SEM2", "Semester 2"),
        ("SEM3", "Semester 3"),
        ("SEM4", "Semester 4"),
        ("SEM5", "Semester 5"),
        ("SEM6", "Semester 6"),
        ("SEM7", "Semester 7"),
        ("SEM8", "Semester 8"),
    )
    subject_semester = models.CharField(max_length=20, choices=SEM_CHOICES)
    education = models.ForeignKey(Education, related_name='kt')


class TeacherProfile(models.Model):
    teacher = models.OneToOneField(User, on_delete=models.CASCADE)
    Sap_Id = models.BigIntegerField(
        validators=[MaxValueValidator(99999999999),
                    MinValueValidator(10000000000)], blank=True, null=True)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    department = models.CharField(max_length=50, blank=True, null=True)
    photo = models.FileField(blank=True, null=True)
    bio = models.CharField(max_length=200, blank=True, null=True)
    GENDER_CHOICES = (
        ("Male", "Male"),
        ("Female", "Female"),
    )
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES, blank=True, null=True)

    class Meta:
        permissions = (
            ("view_teacher", "Can see teacher profile"),
        )

    def __str__(self):
        return str(self.Sap_Id)


'''
class Experience(models.Model):
    employee = models.ForeignKey(TeacherProfile, on_delete=models.CASCADE)
    companyName = models.CharField(max_length=50)
    yourPosition = models.CharField(max_length=50)
    Location = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    date = models.DateField(("Date"), default=datetime.date.today, blank=True)
'''


class Hackathon(models.Model):
    student_profile = models.ForeignKey(StudentProfile, related_name="hackathon")
    CompetitionName = models.CharField(max_length=50, blank=True, null=True)
    Date = models.DateField(blank=True, null=True)
    Desc = models.CharField(max_length=500, blank=True, null=True)
    URL = models.TextField(validators=[URLValidator()], null=True, blank=True)
    image1 = models.FileField(blank=True, null=True)
    image2 = models.FileField(null=True, blank=True)
    image3 = models.FileField(null=True, blank=True)
    image4 = models.FileField(null=True, blank=True)
    image5 = models.FileField(null=True, blank=True)
    history = HistoricalRecords()

    def __str__(self):
        return str(self.CompetitionName)


class Skill(models.Model):
    user_profile = models.ForeignKey(StudentProfile, related_name="skill")
    skill = models.CharField(max_length=50)
    history = HistoricalRecords()

    def __str__(self):
        return str(self.skill)


class Internship(models.Model):
    employee = models.ForeignKey(StudentProfile, related_name="internships")
    company = models.CharField(max_length=50, blank=True, null=True)
    Position = models.CharField(max_length=50, blank=True, null=True)
    Loc = models.CharField(max_length=50, blank=True, null=True)
    From = models.DateField(("Date"), default=datetime.date.today)
    To = models.DateField(("Date"), default=datetime.date.today)
    desc = models.CharField(max_length=500, blank=True, null=True)
    Certificate = models.FileField(blank=True, null=True)
    image1 = models.FileField(blank=True, null=True)
    image2 = models.FileField(blank=True, null=True)
    image3 = models.FileField(blank=True, null=True)
    image4 = models.FileField(blank=True, null=True)
    image5 = models.FileField(blank=True, null=True)
    history = HistoricalRecords()

    def __str__(self):
        return str(self.company)


class Project(models.Model):
    student_profile = models.ForeignKey(
        StudentProfile, related_name="projects")
    ProjName = models.CharField(max_length=50, blank=True, null=True)
    ProjURL = models.TextField(validators=[URLValidator()], blank=True, null=True)
    ProjDesc = models.CharField(max_length=500, blank=True, null=True)
    projectUnderTeacher = models.ForeignKey(
        TeacherProfile, blank=True, related_name="verifiedprojects", null=True)
    skill = models.ForeignKey(
        Skill, related_name="projectskills", blank=True, null=True)
    image1 = models.FileField(blank=True, null=True)
    image2 = models.FileField(blank=True, null=True,)
    image3 = models.FileField(blank=True, null=True,)
    image4 = models.FileField(blank=True, null=True,)
    image5 = models.FileField(blank=True, null=True,)
    history = HistoricalRecords()

    def __str__(self):
        return str(self.ProjName)


class Committee(models.Model):
    employee = models.ForeignKey(StudentProfile, related_name="committee")
    OrganisationName = models.CharField(max_length=50, blank=True, null=True)
    YourPosition = models.CharField(max_length=50, blank=True, null=True)
    Loc = models.CharField(max_length=50, blank=True, null=True)
    dateFrom = models.DateField(
        ("Date"), default=datetime.date.today)
    dateTo = models.DateField(
        ("Date"), default=datetime.date.today)
    Desc = models.CharField(max_length=500, blank=True, null=True)
    Certificate = models.FileField(null=True, blank=True)
    image1 = models.FileField(blank=True, null=True)
    image2 = models.FileField(null=True, blank=True)
    image3 = models.FileField(null=True, blank=True)
    image4 = models.FileField(null=True, blank=True)
    image5 = models.FileField(null=True, blank=True)
    history = HistoricalRecords()

    def __str__(self):
        return str(self.OrganisationName)


class ResearchPaper(models.Model):
    student = models.ForeignKey(StudentProfile, related_name="researchpaper")
    Title = models.CharField(max_length=50, null=True, blank=True)
    Publication = models.CharField(max_length=100, null=True, blank=True)
    DateOfPublication = models.DateField(
        ("Date"), default=datetime.date.today)
    Desc = models.CharField(max_length=500, null=True, blank=True)
    LinkToPaper = models.TextField(validators=[URLValidator()], blank=True, null=True)
    PaperId = models.CharField(max_length=50, null=True, blank=True)
    Published_under = models.ForeignKey(
        TeacherProfile, blank=True, null=True, related_name="verifiedpaper")
    image1 = models.FileField(null=True, blank=True)
    image2 = models.FileField(null=True, blank=True)
    image3 = models.FileField(null=True, blank=True)
    image4 = models.FileField(null=True, blank=True)
    image5 = models.FileField(null=True, blank=True)
    history = HistoricalRecords()

    def __str__(self):
        return str(self.Title)


class BeProject(models.Model):
    student = models.ForeignKey(StudentProfile, related_name='beprojects')

user_profile/templates/user_profile/beproject.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->


  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
{% endblock %}

{% block nav %}
<nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->

      <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">
            <!-- User Account: style can be found in dropdown.less -->
            <li class="dropdown user user-menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <!-- <img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image"> -->

      <span class="hidden-xs">Options</span>

              </a>
              <ul class="dropdown-menu">
                <!-- User image -->
                <li class="user-header">

                  <p>
                    {{ teacher.Sap_Id }}
                  </p>
                </li>
                <!-- Menu Footer-->
                <li class="user-footer">
                  <div class="pull-left">
                    <a href="{% url 'user_profile:student_list' %}" class="btn btn-default btn-flat">Search</a>
                  </div>
                  <div class="pull-left">
                    <a href="{% url 'user_profile:notifs' %}" class="btn btn-default btn-flat">Notifications</a>
                  </div>
                  <div class="pull-left">
                    <a href="{% url 'user_profile:logout_teacher' %}" class="btn btn-default btn-flat">Sign out</a>
                  </div>
                </li>
              </ul>
            </li>
            <!-- Control Sidebar Toggle Button -->
            <li>
              <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
            </li>
          </ul>
        </div>
    </nav>
{% endblock %}

{% block content %}
<section class="content">
  <div class="box">
     <div class="box-header with-border">
       <h3 class="box-title">BE-Project</h3>
     </div>
     <!-- /.box-header -->
     <div class="box-body">
         <dl class="dl-horizontal">

           <dt>Name</dt>
           <dd>: {{ intern.ProjName }} </dd>
           <dt>URL </dt>
           <dd>: {{ intern.ProjURL }} </dd>
           <dt>Description </dt>
           <dd>: {{ intern.ProjDesc }}</dd>
           {% if intern.projectUnderTeacher %}
             <dt>Teacher</dt>
             <dd> : {{ intern.projectUnderTeacher }}  </dd>
           {% endif %}
           {% if intern.teammates.all %}
           <dt>Teammates </dt>
           <dd>:
                 {% for x in intern.teammates.all %}
                       {{ x.Sap_Id }}
                 {% endfor %}
           </dd>
           {% endif %}
           {% if intern.image1 %}
           <dt> Screenshot</dt> :
           <dd>
             <img src="{{ intern.image1.url }}">
             {% endif %}
           {% if intern.image2  %}
           <img src="{{ intern.image2.url }}">
           {% endif %}
           {% if intern.image3  %}
           <img src="{{ intern.image3.url }}">
           {% endif %}
           {% if intern.image4  %}
           <img src="{{ intern.image4.url }}">
           {% endif %}
           {% if intern.image5 %}
           <img src="{{ intern.image5.url }}">
           {% endif %}
           </dd>

       </dl><br>
     </div>
  </div>
</section>
{% endblock %}

user_profile/templates/user_profile/internship.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->


  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
{% endblock %}

{% block nav %}
<nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->

      <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">
            <!-- User Account: style can be found in dropdown.less -->
            <li class="dropdown user user-menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <!-- <img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image"> -->

      <span class="hidden-xs">Options</span>

              </a>
              <ul class="dropdown-menu">
                <!-- User image -->
                <li class="user-header">

                  <p>
                    {{ teacher.Sap_Id }}
                  </p>
                </li>
                <!-- Menu Footer-->
                <li class="user-footer">
                  <div class="pull-left">
                    <a href="{% url 'user_profile:student_list' %}" class="btn btn-default btn-flat">Search</a>
                  </div>
                  <div class="pull-left">
                    <a href="{% url 'user_profile:notifs' %}" class="btn btn-default btn-flat">Notifications</a>
                  </div>
                  <div class="pull-left">
                    <a href="{% url 'user_profile:logout_teacher' %}" class="btn btn-default btn-flat">Sign out</a>
                  </div>
                </li>
              </ul>
            </li>
            <!-- Control Sidebar Toggle Button -->
            <li>
              <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
            </li>
          </ul>
        </div>
    </nav>
{% endblock %}

{% block content %}
<section class="content">
  <div class="box">
     <div class="box-header with-border">
       <h3 class="box-title">Internships</h3>
     </div>
     <!-- /.box-header -->
     <div class="box-body">
         <dl class="dl-horizontal">

           <dt>Company </dt>
           <dd>: {{ intern.company }} </dd>
           <dt>Position </dt>
           <dd>: {{ intern.Position }} </dd>
           <dt>Company Location </dt>
           <dd>: {{ intern.Loc }}</dd>
           {% if intern.From %}
             <dt>Date Started </dt>
             <dd> : {{ intern.From }}  </dd>
           {% endif %}
           {% if intern.To %}
             <dt>Date To </dt>
             <dd>: {{ intern.To }}  </dd>
           {% endif %}
             <dt>Description </dt>
             <dd>: {{ intern.desc }}  </dd>
           {% if intern.Certificate  %}
          <dt> Certificate</dt>
          <dd> :  <img  src="{{ intern.Certificate.url }}">  </dd>
           {% endif %}
           {% if intern.image1 %}
           <dt> Screenshot</dt> :
           <dd>
           <img src="{{ intern.image1.url }}">
           {% endif %}
           {% if intern.image2 %}
           <img src="{{ intern.image2.url }}">
           {% endif %}
           {% if intern.image3%}
           <img src="{{ intern.image3.url }}">
           {% endif %}
           {% if intern.image4 %}
           <img src="{{ intern.image4.url }}">
           {% endif %}
           {% if intern.image5 %}
           <img src="{{ intern.image5.url }}">
           {% endif %}
           </dd>

       </dl><br>
     </div>
  </div>
</section>
{% endblock %}

user_profile/templates/user_profile/login.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static "/build/css/bootstrap.min.css" %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "/build/css/font-awesome.min.css" %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static "/build/css/ionicons.min.css" %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static "/dist/css/AdminLTE.min.css" %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static "/plugins/iCheck/square/blue.css" %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html"><b>Student</b>Login</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>

    <form  action="{% url 'user_profile:user_login'%}" method="post">
      {% csrf_token %}
      <div class="form-group has-feedback">
        <input  class="form-control" placeholder="SAP ID" name="username">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Password" name="password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
        </div>
        <!-- /.col -->
      </div>


    </form>



    <a href="#">I forgot my password</a><br>
    <a href="../../register/student/" class="text-center">Register!</a><br>
    <a href="{% url 'user_profile:user_login_teacher' %}" class="text-center">Are you a Teacher ?</a>

  </div>
  <!-- /.login-box-body -->

</div>
{% if error%}
  <div class="error-page">
    <div class="error-content">
      <h3><i class="fa fa-warning text-yellow"></i> {{ error }}</h3>
    </div>
    <!-- /.error-content -->
  </div>
  <!-- /.error-page -->
{% endif %}
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static "/build/js/jquery.min.js" %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static "/build/js/bootstrap.min.js" %}"></script>
<!-- iCheck -->
<script src="{% static "/plugins/iCheck/icheck.min.js" %}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>

</body>
</html>

user_profile/templates/user_profile/project.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->


  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
{% endblock %}

{% block nav %}
<nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->

      <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">
            <!-- User Account: style can be found in dropdown.less -->
            <li class="dropdown user user-menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <!-- <img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image"> -->

      <span class="hidden-xs">Options</span>

              </a>
              <ul class="dropdown-menu">
                <!-- User image -->
                <li class="user-header">

                  <p>
                    {{ teacher.Sap_Id }}
                  </p>
                </li>
                <!-- Menu Footer-->
                <li class="user-footer">
                  <div class="pull-left">
                    <a href="{% url 'user_profile:student_list' %}" class="btn btn-default btn-flat">Search</a>
                  </div>
                  <div class="pull-left">
                    <a href="{% url 'user_profile:notifs' %}" class="btn btn-default btn-flat">Notifications</a>
                  </div>
                  <div class="pull-left">
                    <a href="{% url 'user_profile:logout_teacher' %}" class="btn btn-default btn-flat">Sign out</a>
                  </div>
                </li>
              </ul>
            </li>
            <!-- Control Sidebar Toggle Button -->
            <li>
              <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
            </li>
          </ul>
        </div>
    </nav>
{% endblock %}

{% block content %}
<section class="content">
  <div class="box">
     <div class="box-header with-border">
       <h3 class="box-title">Projects</h3>
     </div>
     <!-- /.box-header -->
     <div class="box-body">
         <dl class="dl-horizontal">

           <dt>Name</dt>
           <dd>: {{ intern.ProjName }} </dd>
           <dt>URL </dt>
           <dd>: {{ intern.ProjURL }} </dd>
           <dt>Description </dt>
           <dd>: {{ intern.ProjDesc }}</dd>
           {% if intern.projectUnderTeacher %}
             <dt>Teacher</dt>
             <dd> : {{ intern.projectUnderTeacher }}  </dd>
           {% endif %}
           <dt>Skill </dt>
           <dd>: {{ intern.skill }}</dd>
           {% if intern.image1 %}
           <dt> Screenshot</dt> :
           <dd>
             <img src="{{ intern.image1.url }}">
             {% endif %}
           {% if intern.image2  %}
           <img src="{{ intern.image2.url }}">
           {% endif %}
           {% if intern.image3  %}
           <img src="{{ intern.image3.url }}">
           {% endif %}
           {% if intern.image4  %}
           <img src="{{ intern.image4.url }}">
           {% endif %}
           {% if intern.image5  %}
           <img src="{{ intern.image5.url }}">
           {% endif %}
           </dd>

       </dl><br>
     </div>
  </div>
</section>
{% endblock %}