info_portal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('user_profile.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_profile/urls.py
from django.conf.urls import url
from . import views

app_name = 'user_profile'
urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^register/student/$', views.register, name='register'),
    url(r'^login/student/$', views.user_login, name='user_login'),
    url(r'^register/teacher/$', views.register_teacher, name='register_teacher'),
    url(r'^login/teacher/$', views.user_login_teacher, name='user_login_teacher'),
    url(r'^logout/student/$', views.logout_student, name='logout_student'),
    url(r'^logout/teacher/$', views.logout_teacher, name='logout_teacher'),
    url(r'^login/recruiter/$', views.user_login_recruiter,
        name='user_login_recruiter'),
    url(r'^logout/recruiter/$', views.logout_recruiter, name='logout_recruiter'),
    url(r'^student_profile/(\d+)$',
        views.student_profile, name='student_profile'),
    url(r'^notifications/$', views.notifs, name='notifs'),
    url(r'^search/$', views.student_list, name='student_list'),
    url(r'^teacherdashboard/$', views.teacher_dashboard, name='teacher_dashboard'),
    url(r'^search/$', views.student_list, name='student_list'),
    url(r'^internship/(\d+)$', views.internship, name='internship'),
    url(r'^hackathon/(\d+)$', views.hackathon, name='hackathon'),
    url(r'^project/(\d+)$', views.project, name='project'),
    url(r'^beproject/(\d+)$', views.beproject, name='beproject'),
    url(r'^committee/(\d+)$', views.committee, name='committee'),
    url(r'^researchpaper/(\d+)$', views.researchpaper, name='researchpaper'),
    url(r'^extracurricular/(\d+)$', views.extracurricular, name='extracurricular'),
    url(r'^searchany/', views.searchany, name='searchany'),
    url(r'^editprofile', views.show_edit_studentprofile, name='show_edit_studentprofile'),
    url(r'^edit_basic_info/(\d+)$', views.edit_basic_info),
    url(r'^edit_academic_info/(\d+)$', views.edit_academic_info),
    url(r'^edit_skill_info/(\d+)$', views.edit_skill_info),
    url(r'^edit_hackathon_info/(\d+)$', views.edit_hackathon_info),
    url(r'^edit_project_info/(\d+)$', views.edit_project_info),
    url(r'^edit_internship_info/(\d+)$', views.edit_internship_info),
    url(r'^edit_committee_info/(\d+)$', views.edit_committee_info),
    url(r'^edit_research_paper_info/(\d+)$', views.edit_research_paper_info),
    url(r'^edit_beproject_info/(\d+)$', views.edit_beproject_info),
    url(r'^delete_project_info/(\d+)$', views.delete_project_info),
    url(r'^delete_hackathon_info/(\d+)$', views.delete_hackathon_info),
    url(r'^delete_committee_info/(\d+)$', views.delete_committee_info),
    url(r'^delete_skill_info/(\d+)$', views.delete_skill_info),
    url(r'^delete_internship_info/(\d+)$', views.delete_internship_info),
    url(r'^delete_researchpaper_info/(\d+)$', views.delete_researchpaper_info),
    url(r'^delete_extra_info/(\d+)$', views.delete_extra_info),
    url(r'^edit_extra_info/(\d+)$', views.edit_extra_info),
]

user_profile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from .models import (StudentProfile, TeacherProfile, Internship, Project, Committee, ResearchPaper, BeProject,
                     Hackathon, Skill, Education, ExtraCurricular, KT)
from .models import (HistoricalInternship, HistoricalProject, HistoricalCommittee, HistoricalResearchPaper,
                     HistoricalBeProject, HistoricalHackathon, HistoricalEducation, HistoricalExtraCurricular)
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.models import User
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
import collections
from django.utils.dateformat import format
from django.core.exceptions import ObjectDoesNotExist
import datetime
import os
import requests


def homepage(request):
    return render(request, 'index.html')


def show_rollingform(request):
    return render(request, 'user_profile/edit_student_profile.html')


def register(request):
    if request.user.is_authenticated:
        student_profile = StudentProfile.objects.get(student=request.user)
        student_profile_url = '/student_profile/' + str(student_profile.id)
        return HttpResponseRedirect(student_profile_url)
    else:
        if request.method == 'POST':
            username = request.POST.get('Sap_Id', '')
            password = request.POST.get('password', '')
            email = request.POST.get('email', '')
            Sap_Id = request.POST.get('Sap_Id', '')
            first_name = request.POST.get('first_name', '')
            last_name = request.POST.get('last_name', '')

            if User.objects.filter(username=username).exists():
                error = 'The Sap_id is already in use by another account.'
                return render(request, 'user_profile/registration.html', {'error': error})

            else:
                user = User.objects.create_user(username=username, email=email)
                user.set_password(password)
                user.save()
                content_type = ContentType.objects.get_for_model(
                    StudentProfile)
                permission = Permission.objects.get(
                    content_type=content_type, codename='view_student')
                user.user_permissions.add(permission)
                sap = str(Sap_Id)
                student = StudentProfile.objects.create(
                    student=user, Sap_Id=Sap_Id, sap=sap, first_name=first_name,
                    last_name=last_name)
                student.save()
                auth_login(request, user)
                student_profile_url = '/student_profile/' + str(student.id)
                return HttpResponseRedirect(student_profile_url)
                # return render(request, 'user_profile/profile.html', {"student": student})
        else:
            return render(request, 'user_profile/registration.html', {})


def user_login(request):
    if request.user.is_authenticated:
        student_profile = StudentProfile.objects.get(student=request.user)
        student_profile_url = '/student_profile/' + str(student_profile.id)
        return HttpResponseRedirect(student_profile_url)
    else:
        if request.method == 'POST':
            username = request.POST.get('username', '')
            password = request.POST.get('password', '')
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    auth_login(request, user)
                    # return render(request, 'user_profile/profile.html', {})
                    student_profile = StudentProfile.objects.get(
                        student=request.user)
                    student_profile_url = '/student_profile/' + \
                        str(student_profile.id)
                    return HttpResponseRedirect(student_profile_url)
                else:
                    error = 'Your account is disabled.'
                    return render(request, 'user_profile/login.html', {'error': error})
            else:
                error = 'Incorrect Username or Password'
                return render(request, 'user_profile/login.html', {'error': error})
        else:
            return render(request, 'user_profile/login.html', {})


def register_teacher(request):
    if request.user.is_authenticated:
        teacher_profile_url = '/teacherdashboard/'
        return HttpResponseRedirect(teacher_profile_url)
    else:
        if request.method == 'POST':
            username = request.POST.get('Sap_Id', '')
            password = request.POST.get('password', '')
            email = request.POST.get('email', '')
            Sap_Id = request.POST.get('Sap_Id', '')
            first_name = request.POST.get('first_name', '')
            last_name = request.POST.get('last_name', '')

            if User.objects.filter(username=username).exists():
                error = 'The Sap_id is already in use by another account.'
                return render(request, 'user_profile/registration_teacher.html', {'error': error})

            else:
                user = User.objects.create_user(username=username, email=email)
                user.set_password(password)
                content_type = ContentType.objects.get_for_model(
                    TeacherProfile)
                permission = Permission.objects.get(
                    content_type=content_type, codename='view_teacher')
                user.user_permissions.add(permission)
                content_type = ContentType.objects.get_for_model(
                    StudentProfile)
                permission = Permission.objects.get(
                    content_type=content_type, codename='view_student')
                user.user_permissions.add(permission)
                ct = ContentType.objects.get_for_model(StudentProfile)
                permission = Permission.objects.get(
                    codename='delete_studentprofile', content_type=ct)
                user.user_permissions.add(permission)
                ct = ContentType.objects.get_for_model(Internship)
                permission = Permission.objects.get(
                    codename='delete_internship', content_type=ct)
                user.user_permissions.add(permission)
                ct = ContentType.objects.get_for_model(Project)
                permission = Permission.objects.get(
                    codename='delete_project', content_type=ct)
                user.user_permissions.add(permission)
                ct = ContentType.objects.get_for_model(Committee)
                permission = Permission.objects.get(
                    codename='delete_committee', content_type=ct)
                user.user_permissions.add(permission)
                ct = ContentType.objects.get_for_model(ResearchPaper)
                permission = Permission.objects.get(
                    codename='delete_researchpaper', content_type=ct)
                user.user_permissions.add(permission)
                ct = ContentType.objects.get_for_model(BeProject)
                permission = Permission.objects.get(
                    codename='delete_beproject', content_type=ct)
                user.user_permissions.add(permission)
                user.save()
                teacher = TeacherProfile.objects.create(
                    teacher=user, Sap_Id=Sap_Id, first_name=first_name,
                    last_name=last_name)
                teacher.save()
                auth_login(request, user)
                teacher_profile_url = '/teacherdashboard/'
                return HttpResponseRedirect(teacher_profile_url)
        else:
            return render(request, 'user_profile/registration_teacher.html', {})


def user_login_teacher(request):
    if request.user.is_authenticated:
        teacher_profile_url = '/teacherdashboard/'
        return HttpResponseRedirect(teacher_profile_url)
    else:
        if request.method == 'POST':
            username = request.POST.get('username', '')
            password = request.POST.get('password', '')
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    auth_login(request, user)
                    teacher_profile_url = '/teacherdashboard/'
                    return HttpResponseRedirect(teacher_profile_url)
                else:
                    error = 'Your account is disabled.'
                    return render(request, 'user_profile/teacher_login.html', {'error': error})
            else:
                error = 'Incorrect Username or Password'
                return render(request, 'user_profile/teacher_login.html', {'error': error})
        else:
            return render(request, 'user_profile/teacher_login.html', {})


def logout_student(request):
    auth_logout(request)
    return redirect(reverse('user_profile:user_login'))


def logout_teacher(request):
    auth_logout(request)
    return redirect(reverse('user_profile:user_login_teacher'))


def logout_recruiter(request):
    auth_logout(request)
    return redirect(reverse('user_login_recruiter'))


def user_login_recruiter(request):
    if request.user.is_authenticated:
        return render(request, 'user_profile/recruiter.html', {})
    else:
        if request.method == 'POST':
            username = request.POST.get('username', '')
            password = request.POST.get('password', '')
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    auth_login(request, user)

user_profile/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Unicode</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static "/build/css/bootstrap.min.css" %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "/build/css/font-awesome.min.css" %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static "/build/css/ionicons.min.css" %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static "/dist/css/AdminLTE.min.css" %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static "/dist/css/skins/_all-skins.min.css" %}">
  <!-- Morris chart -->
  <!-- <link rel="stylesheet" href="{% static "/build/css/morris.css" %}"> -->
  <!-- jvectormap -->
  <link rel="stylesheet" href="{% static "/build/css/jquery-jvectormap.css" %}">
  <!-- Date Picker -->
  <link rel="stylesheet" href="{% static "/build/css/bootstrap-datepicker.min.css" %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static "/build/css/daterangepicker.css" %}">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="{% static "/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
<style>
.navbar-nav>.user-menu>.dropdown-menu>li.user-header {
    padding: 10px;
    text-align: center;
}
</style>
  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  {% block css %}
  {% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b><\></b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Unicode</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    {% block nav %}
    {% endblock %}
  </header>
  <!-- Left side column. contains the logo and sidebar -->

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" style="margin-left:0px;">
    <!-- Content Header (Page header) -->
    {% block content %}
    {%endblock%}

  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer" style="margin-left:0px;">
    <div class="pull-right hidden-xs">
    </div>
    <strong>Made with lots of Love By Unicode TEAM2.</strong>
  </footer>

</div>
<!-- ./wrapper -->

<!-- jQuery 3 -->
<script src="{% static "/build/js/jquery.min.js" %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static "/build/js/jquery-ui.min.js" %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static "/build/js/bootstrap.min.js" %}"></script>
<!-- Morris.js charts -->
<script src="{% static "/build/js/raphael.min.js" %}"></script>
<!-- <script src="{% static "/build/js/morris.min.js" %}"></script> -->
<!-- Sparkline -->
<script src="{% static "/build/js/jquery.sparkline.min.js" %}"></script>
<!-- jvectormap -->
<script src="{% static "/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" %}"></script>
<script src="{% static "/plugins/jvectormap/jquery-jvectormap-world-mill-en.js" %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static "/build/js/jquery.knob.min.js" %}"></script>
<!-- daterangepicker -->
<script src="{% static "/build/js/moment.min.js" %}"></script>
<script src="{% static "/build/js/daterangepicker.js" %}"></script>
<!-- datepicker -->
<script src="{% static "/build/js/bootstrap-datepicker.min.js" %}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{% static "/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" %}"></script>
<!-- Slimscroll -->
<script src="{% static "/build/js/jquery.slimscroll.min.js" %}"></script>
<!-- FastClick -->
<script src="{% static "/build/js/fastclick.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "/dist/js/adminlte.min.js" %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<!-- <script src="{% static "/dist/js/pages/dashboard.js" %}"></script> -->
<!-- AdminLTE for demo purposes -->
<script src="{% static "/dist/js/demo.js" %}"></script>
{% block js %}
{% endblock %}
</body>
</html>

user_profile/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en"><head>
  <meta charset="utf-8">
  <title>Landing Page</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  <meta property="og:title" content="">
	<meta property="og:type" content="website">
	<meta property="og:url" content="">
	<meta property="og:site_name" content="">
	<meta property="og:description" content="">

  <!-- Styles -->
  <link rel="stylesheet" href="{% static 'build/css/font-awesome.min.css'%}">
  <link rel="stylesheet" href="{% static 'build/css/animate.css' %}">
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900|Montserrat:400,700' rel='stylesheet' type='text/css'>


  <link rel="stylesheet" href="{% static 'build/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'build/css/main.css' %}">

  <script src="{% static 'build/js/modernizr-2.7.1.js' %}"></script>

</head>

<body>

<!-- navbar code -->
    <!-- <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="logo" href="index.html"><img src="img/logo.svg" alt="Logo"></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#pricing" class="scroll">Pricing</a></li>
            <li><a href="#">Sign in</a></li>
          </ul>
        </div>
      </div>
    </div> -->

    <header>
      <div class="container">
        <div class="row">
          <div class="col-xs-6">

          </div>
          <div class="col-xs-6 signin text-right navbar-nav">
            <a href="index.html"><img src="{% static 'build/img/logo.png' %}" alt="Logo"></a>
          </div>
        </div>

        <div class="row header-info">
          <div class="col-sm-10 col-sm-offset-1 text-center">
            <h1 class="wow fadeIn">DJ Comps Student Information Portal</h1>
            <br />
            <p class="lead wow fadeIn" data-wow-delay="0.5s">
              Contains information about Internships, Grades, Volunteer work, of students <br> for reference
               of teachers, recruiters and the department.

            </p>
            <br />

            <div class="row">
              <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
                <div class="row">
                  <div class="col-xs-6 text-right wow fadeInUp" data-wow-delay="1s">
                    <a href="{% url 'user_profile:user_login' %}" class="btn btn-secondary btn-lg">STUDENT <br> Sign-in</a>
                    <a href="{% url 'user_profile:user_login_teacher' %}" class="btn btn-secondary btn-lg">TEACHER <br> Sign-in</a>
                  </div>
                  <div class="col-xs-6 text-left wow fadeInUp" data-wow-delay="1.4s">
                    <a href="{% url 'user_profile:register' %}" class="btn btn-primary btn-lg">STUDENT <br>Register</a>
                    <a href="{% url 'user_profile:register_teacher' %}" class="btn btn-primary btn-lg">TEACHER <br>Register</a>
                  </div>
                </div><!--End Button Row-->
              </div>
            </div>

          </div>
        </div>
      </div>
    </header>

    <div class="mouse-icon hidden-xs">
				<div class="scroll"></div>
			</div>

    <section id="be-the-first" class="pad-xl">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-sm-offset-2 text-center margin-30 wow fadeIn" data-wow-delay="0.6s">
            <h2>Be the first !</h2>
          </div>
        </div>

        <div class="iphone wow fadeInUp" data-wow-delay="1s" style="margin-left: 95px;">
	        <img src="{% static 'build/img/iphone.png' %}">
        </div>
      </div>
    </section>

    <section id="main-info" class="pad-xl">
	    <div class="container" style="margin-top: 200px;">
		    <div class="row">
			    <div class="col-sm-4 wow fadeIn" data-wow-delay="0.4s">
				    <hr class="line purple">
				    <h3>Verified Profiles</h3>
				    <p>To ensure that the information added by the student is not fake, a system of verification is used for every update a student makes to his/her profile.</p>
			    </div>
			    <div class="col-sm-4 wow fadeIn" data-wow-delay="0.8s">
				    <hr  class="line blue">
				    <h3>Three Level of User Permissions:</h3>
				    <p>A superuser, a teacher and the student. The student has the most basic access rights, the teacher verifies student information.</p>
			    </div>
			    <div class="col-sm-4 wow fadeIn" data-wow-delay="1.2s">
				    <hr  class="line yellow">
				    <h3>Dashboard for Student and Teachers</h3>
				    <p>A dashboard facility with interactive forms for students and teachers to regularly update profiles.</p>
			    </div>
		    </div>
        <div class="row">
			    <div class="col-sm-4 wow fadeIn" data-wow-delay="0.4s">
				    <hr class="line purple">
				    <h3>Filter-based Results</h3>
				    <p>For ease of use by teachers and recruiters, profiles can be filtered based on area of interest, research aptitude, projects, competitive coding skills etc.</p>
			    </div>
			    <div class="col-sm-4 wow fadeIn" data-wow-delay="0.8s">
				    <hr  class="line blue">
				    <h3>Profile Updation and Analysis</h3>
				    <p>Whenever a student updates his/her profile, it can be viewed by all as a student progress in the respective domain. Analysis is carried out to show how much progress is carried it in the domain in how much time.</p>
			    </div>
			    <div class="col-sm-4 wow fadeIn" data-wow-delay="1.2s">
				    <hr  class="line yellow">
				    <h3>Connecting teachers and students:</h3>
				    <p>When students take up projects under a college professor, the system users can view the professor portfolio and project details on the portal.</p>
			    </div>
		    </div>
	    </div>
    </section>


    <!--Pricing-->
    <section id="pricing" class="pad-lg">
      <div class="container">
        <div class="row margin-40">
          <div class="col-sm-8 col-sm-offset-2 text-center">
            <h2 class="white">Team</h2>
            <p class="white">Team Leader: Rudresh Panchal</p>
          </div>
        </div>

        <div class="row margin-50">
          <div class="col-sm-4 pricing-container wow fadeInUp" data-wow-delay="1s">
            <br/>
            <ul class="list-unstyled pricing-table text-center">
              <li class="headline"><h5 class="white">Front End Developers</h5></li>
              <li class="info"></li>
              <li class="features first">Parth Mehta</li>
              <li class="features">Sanika Potdar</li>
              <li class="features">Kushal Doshi</li>
              <li class="features">Vishesh Vohra</li>
            </ul>
          </div>

          <div class="col-sm-4 pricing-container wow fadeInUp" data-wow-delay="0.4s">
            <ul class="list-unstyled pricing-table active text-center">
              <li class="headline"><h5 class="white">Mentors</h5></li>
              <li class="info" style="color:#fff;" >........................<b> Team Leader: Rudresh Panchal </b>........................</li>
              <li class="features">Vishal Jain</li>
              <li class="features">Krutik Menkudle</li>
              <li class="features">Shraddha Shaligram</li>
              <li class="features">Saumya Shah</li>
            </ul>
          </div>

          <div class="col-sm-4 pricing-container wow fadeInUp" data-wow-delay="1.3s">
            <br/>
            <ul class="list-unstyled pricing-table text-center">
              <li class="headline"><h5 class="white">Back End Developers</h5></li>
              <li class="info"></li>
              <li class="features first">Ayush Kothari</li>
              <li class="features">Sarvesh Joglekar</li>
              <li class="features">Siddhant Soni</li>
              <li class="features" style="color:#fff;">Siddhant Soni</li>
            </ul>
          </div>
        </div>
      </div>
    </section>

    <!-- Javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static 'build/js/jquery-1.11.0.min.js' %}"><\/script>')</script>
    <script src="{% static 'build/js/wow.min.js' %}"></script>
    <script src="{% static 'build/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'build/js/main.js' %}"></script>


    </body>
</html>